### ISSUE TITLE
HDRP version

### ISSUE THREAD

**Issue by cbanwell** [aniruddhahar/URP-AnimatedGrass#1]
Hi, How would I change the masternode for this to work in HDRP?  Sorry complete novice when it comes to ShaderGraph

**Comment by aniruddhahar** [comment]
I haven't checked this in HDRP yet but it should be simple enough.

You can open the shadergraph in an HDRP project, and then add a Lit Master node. The connections, and other unconnected values to this node should be the same as the ones for URP's PBR master node. Right click on the new master node and set it to active and it should work.

**Comment by aniruddhahar** [comment]
> Hi, How would I change the masternode for this to work in HDRP?  Sorry complete novice when it comes to ShaderGraph

I haven't checked this in HDRP yet but it should be simple enough.

You can open the shadergraph in an HDRP project, and then add a Lit Master node. The connections, and other unconnected values to this node should be the same as the ones for URP's PBR master node. Right click on the new master node and set it to active and it should work.

**Comment by cbanwell** [comment]
Thanks that worked :)
